void appendStringArr(char *string, char c, int arrayLength);
void selectionInt(int pptargetArray[], int sizeOfArray);
void selectionString(char *ptargetArray[], int sizeOfArray);
void  insertionInt(int targetArray[], int sizeOfArray);
void  insertionString(char *ptargetArray[], int sizeOfArray);
void radixSortStr(char* arr[], int arrLen);
int getMaxStr(char* arr[], int arrLen);
void countSortStr(char* arr[], int ind);
void radixSortInt(int arr[], int arrLen);
int getMaxInt(int arr[], int arrLen);
void countSortInt(int arr[], int arrLen, int ind);
void heapSortString(char *arr[], int arrLen);
void heapifyString(char *arr[], int arrLen, int i);
void heapSortInt(int arr[], int n);
void heapifyInt(int arr[], int n, int i);
